FROM quay.io/ukhomeofficedigital/pttg-bdd-base

ENV PTTG_API_ENDPOINT localhost
ENV USER pttg
ENV GROUP pttg
ENV NAME pttg-fs-ui

ARG VERSION

WORKDIR /app

RUN groupadd -r ${GROUP} && \
    useradd -r -g ${GROUP} ${USER} -d /app && \
    mkdir -p /app && \
    chown -R ${USER}:${GROUP} /app

COPY . /app
RUN npm --loglevel warn install
RUN npm --loglevel warn run postinstall
RUN npm install chromedriver@2.32.3

RUN chown -R ${USER}:${GROUP} /app

USER pttg

ENTRYPOINT /app/run-test.sh
