FROM quay.io/ukhomeofficedigital/nodejs-base:v6.9.1

ENV PTTG_API_ENDPOINT localhost
ENV USER pttg
ENV GROUP pttg
ENV NAME pttg-fs-ui

ARG VERSION

WORKDIR /app

RUN groupadd -r ${GROUP} && \
    useradd -r -g ${GROUP} ${USER} -d /app && \
    mkdir -p /app && \
    chown -R ${USER}:${GROUP} /app

COPY . /app


RUN yum install -y bzip2
RUN yum install -y fontconfig
RUN npm --loglevel warn install --only=dev
RUN ./node_modules/.bin/gulp

COPY google-chrome.repo /etc/yum.repos.d/
RUN yum install -y gnu-free-sans-fonts
RUN yum install -y google-chrome-stable
RUN yum install -y xorg-x11-server-Xvfb
RUN Xvfb -ac :99 -screen 0 1680x1050x24 &
RUN export DISPLAY=:99

RUN mkdir /app/report
RUN chown -R ${USER}:${GROUP} /app

USER pttg

ENTRYPOINT /app/run-test.sh
